# Generated by Django 2.2.2 on 2019-06-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItBoom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(default='new', max_length=255),
        ),
        migrations.AddField(
            model_name='offermessage',
            name='status',
            field=models.CharField(default='new', max_length=255),
        ),
    ]
