# Generated by Django 2.2.2 on 2019-06-11 14:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ItBoom', '0002_auto_20190611_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runablednews',
            name='title',
            field=tinymce.models.HTMLField(verbose_name='title'),
        ),
    ]
