# Generated by Django 2.2.2 on 2019-06-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItBoom', '0004_auto_20190611_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='offermessage',
            name='message',
            field=models.TextField(),
        ),
    ]
