# Generated by Django 2.2.2 on 2019-06-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItBoom', '0005_auto_20190611_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerlanguage',
            name='index',
            field=models.FloatField(default=0),
        ),
    ]
