# Generated by Django 2.2.2 on 2019-06-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItBoom', '0006_auto_20190612_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('song_artist', models.CharField(max_length=255)),
                ('song_record', models.FileField(upload_to='')),
            ],
        ),
    ]
